language: ruby
rvm:
  - "2.0.0"
script: bundle exec rake all
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
  code_climate:
    repo_token: 7621e981cace82896b9e32411111c62e2eab7fba1c7794d615916aaa9055f276
cache: bundler
sudo: false
